spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
    # Release DB
    url: jdbc:postgresql://192.168.253.3:5432/ict?currentSchema=public
    username: ict
    password: '#HE0m4K12:bqZ1YQ'
    driverClassName: org.postgresql.Driver
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb